# Generated by Django 4.2.4 on 2023-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_homemotto_title1_remove_homemotto_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemotto',
            name='title',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homemotto',
            name='titlee',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
