# Generated by Django 4.2.4 on 2023-08-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_courses_schedule_courses_seats_courses_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='money2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='money',
            field=models.CharField(max_length=30),
        ),
    ]
