# Generated by Django 4.2.4 on 2023-08-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_courses_money2_alter_courses_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coursedetails',
        ),
    ]
